// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import "strconv"

type OrderSide int8

const (
	OrderSideUNKNOWN OrderSide = 0
	OrderSideBID     OrderSide = 1
	OrderSideASK     OrderSide = 2
)

var EnumNamesOrderSide = map[OrderSide]string{
	OrderSideUNKNOWN: "UNKNOWN",
	OrderSideBID:     "BID",
	OrderSideASK:     "ASK",
}

var EnumValuesOrderSide = map[string]OrderSide{
	"UNKNOWN": OrderSideUNKNOWN,
	"BID":     OrderSideBID,
	"ASK":     OrderSideASK,
}

func (v OrderSide) String() string {
	if s, ok := EnumNamesOrderSide[v]; ok {
		return s
	}
	return "OrderSide(" + strconv.FormatInt(int64(v), 10) + ")"
}
