// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import "strconv"

type OrderUpdateType int8

const (
	OrderUpdateTypeUNKNOWN  OrderUpdateType = 0
	OrderUpdateTypeRECEIVED OrderUpdateType = 1
	OrderUpdateTypeOPEN     OrderUpdateType = 2
	OrderUpdateTypeDONE     OrderUpdateType = 3
	OrderUpdateTypeMATCH    OrderUpdateType = 4
	OrderUpdateTypeCHANGE   OrderUpdateType = 5
)

var EnumNamesOrderUpdateType = map[OrderUpdateType]string{
	OrderUpdateTypeUNKNOWN:  "UNKNOWN",
	OrderUpdateTypeRECEIVED: "RECEIVED",
	OrderUpdateTypeOPEN:     "OPEN",
	OrderUpdateTypeDONE:     "DONE",
	OrderUpdateTypeMATCH:    "MATCH",
	OrderUpdateTypeCHANGE:   "CHANGE",
}

var EnumValuesOrderUpdateType = map[string]OrderUpdateType{
	"UNKNOWN":  OrderUpdateTypeUNKNOWN,
	"RECEIVED": OrderUpdateTypeRECEIVED,
	"OPEN":     OrderUpdateTypeOPEN,
	"DONE":     OrderUpdateTypeDONE,
	"MATCH":    OrderUpdateTypeMATCH,
	"CHANGE":   OrderUpdateTypeCHANGE,
}

func (v OrderUpdateType) String() string {
	if s, ok := EnumNamesOrderUpdateType[v]; ok {
		return s
	}
	return "OrderUpdateType(" + strconv.FormatInt(int64(v), 10) + ")"
}
