// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import "strconv"

type OrderStatus int8

const (
	OrderStatusUNKNOWN           OrderStatus = 0
	OrderStatusIN_FLIGHT         OrderStatus = 1
	OrderStatusCANCEL_IN_FLIGHT  OrderStatus = 2
	OrderStatusREPLACE_IN_FLIGHT OrderStatus = 3
	OrderStatusNEW               OrderStatus = 4
	OrderStatusACCEPTED          OrderStatus = 5
	OrderStatusCANCELLED         OrderStatus = 6
	OrderStatusREPLACED          OrderStatus = 7
	OrderStatusREJECTED          OrderStatus = 8
	OrderStatusCANCEL_REJECTED   OrderStatus = 9
	OrderStatusREPLACE_REJECTED  OrderStatus = 10
	OrderStatusFILLED            OrderStatus = 11
	OrderStatusPARTIALLY_FILLED  OrderStatus = 12
	OrderStatusEXPIRED           OrderStatus = 13
	OrderStatusDONE              OrderStatus = 14
)

var EnumNamesOrderStatus = map[OrderStatus]string{
	OrderStatusUNKNOWN:           "UNKNOWN",
	OrderStatusIN_FLIGHT:         "IN_FLIGHT",
	OrderStatusCANCEL_IN_FLIGHT:  "CANCEL_IN_FLIGHT",
	OrderStatusREPLACE_IN_FLIGHT: "REPLACE_IN_FLIGHT",
	OrderStatusNEW:               "NEW",
	OrderStatusACCEPTED:          "ACCEPTED",
	OrderStatusCANCELLED:         "CANCELLED",
	OrderStatusREPLACED:          "REPLACED",
	OrderStatusREJECTED:          "REJECTED",
	OrderStatusCANCEL_REJECTED:   "CANCEL_REJECTED",
	OrderStatusREPLACE_REJECTED:  "REPLACE_REJECTED",
	OrderStatusFILLED:            "FILLED",
	OrderStatusPARTIALLY_FILLED:  "PARTIALLY_FILLED",
	OrderStatusEXPIRED:           "EXPIRED",
	OrderStatusDONE:              "DONE",
}

var EnumValuesOrderStatus = map[string]OrderStatus{
	"UNKNOWN":           OrderStatusUNKNOWN,
	"IN_FLIGHT":         OrderStatusIN_FLIGHT,
	"CANCEL_IN_FLIGHT":  OrderStatusCANCEL_IN_FLIGHT,
	"REPLACE_IN_FLIGHT": OrderStatusREPLACE_IN_FLIGHT,
	"NEW":               OrderStatusNEW,
	"ACCEPTED":          OrderStatusACCEPTED,
	"CANCELLED":         OrderStatusCANCELLED,
	"REPLACED":          OrderStatusREPLACED,
	"REJECTED":          OrderStatusREJECTED,
	"CANCEL_REJECTED":   OrderStatusCANCEL_REJECTED,
	"REPLACE_REJECTED":  OrderStatusREPLACE_REJECTED,
	"FILLED":            OrderStatusFILLED,
	"PARTIALLY_FILLED":  OrderStatusPARTIALLY_FILLED,
	"EXPIRED":           OrderStatusEXPIRED,
	"DONE":              OrderStatusDONE,
}

func (v OrderStatus) String() string {
	if s, ok := EnumNamesOrderStatus[v]; ok {
		return s
	}
	return "OrderStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
