// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PriceLevel struct {
	_tab flatbuffers.Struct
}

func (rcv *PriceLevel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PriceLevel) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *PriceLevel) Price() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *PriceLevel) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *PriceLevel) Quantity() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *PriceLevel) MutateQuantity(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreatePriceLevel(builder *flatbuffers.Builder, price float64, quantity float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(quantity)
	builder.PrependFloat64(price)
	return builder.Offset()
}
