// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import "strconv"

type Side int8

const (
	SideUNKNOWN Side = 0
	SideBUY     Side = 1
	SideSELL    Side = 2
)

var EnumNamesSide = map[Side]string{
	SideUNKNOWN: "UNKNOWN",
	SideBUY:     "BUY",
	SideSELL:    "SELL",
}

var EnumValuesSide = map[string]Side{
	"UNKNOWN": SideUNKNOWN,
	"BUY":     SideBUY,
	"SELL":    SideSELL,
}

func (v Side) String() string {
	if s, ok := EnumNamesSide[v]; ok {
		return s
	}
	return "Side(" + strconv.FormatInt(int64(v), 10) + ")"
}
