// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package serialization

import "strconv"

type TimeInForce int8

const (
	TimeInForceDAY TimeInForce = 0
	TimeInForceIOC TimeInForce = 1
	TimeInForceFOK TimeInForce = 2
	TimeInForceGTC TimeInForce = 3
	TimeInForceGTT TimeInForce = 4
)

var EnumNamesTimeInForce = map[TimeInForce]string{
	TimeInForceDAY: "DAY",
	TimeInForceIOC: "IOC",
	TimeInForceFOK: "FOK",
	TimeInForceGTC: "GTC",
	TimeInForceGTT: "GTT",
}

var EnumValuesTimeInForce = map[string]TimeInForce{
	"DAY": TimeInForceDAY,
	"IOC": TimeInForceIOC,
	"FOK": TimeInForceFOK,
	"GTC": TimeInForceGTC,
	"GTT": TimeInForceGTT,
}

func (v TimeInForce) String() string {
	if s, ok := EnumNamesTimeInForce[v]; ok {
		return s
	}
	return "TimeInForce(" + strconv.FormatInt(int64(v), 10) + ")"
}
